/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */

#include <avr/io.h>
#include <config.h>
#include <isp.h>
#include <usart.h>
#include <spi.h>
#include <util/delay.h>
#include <stdint.h>

void init_io(void)
{
	usart0_init();
}	

void capture(void)
{
	DDRB=0;
	PORTB = 0;
	DDRB = (1<<PB0);			//Reset Target
	_delay_ms(10);
	DDRB |= (1<<PB1);		//Set SCK to 0
	_delay_ms(10);
	DDRB &= ~(1<<PB0); 	//Release Reset (High)
	_delay_ms(10);
	DDRB |= (1<<PB0); 		//Pull Reset to low
}

uint8_t enterProgrammingMode(void)
{
	uint8_t temp;
	spi_send(0xAC);
	spi_send(0x53);
	temp = spi_send(0);
	spi_send(0);

	if(temp == 0x53)
		return 0;
	return 1;
}

int main(void)
{
	uint8_t temp;
	init_io();
	sei();
	capture();
	spi_init();
	temp = enterProgrammingMode();
	if(temp==0)
		usart0_putc('0');
	else
		usart0_putc('1');
	while(1);
	return (0);
}
